### ISSUE TITLE
Validate file integrity

### ISSUE THREAD

**Issue by alistaire47** [conbench/datalogistik#1]
Historically {ursacomputing/benchmarks} has validated file integrity by checking file size equals an expected size. Because a lot of factors can impact file size, this became a pain, but the idea of validating that files used for benchmarks are consistent is still worthwhile, if we have a robust way to test it. This PR removed the validation, showing exactly what was done: https://github.com/ursacomputing/benchmarks/pull/117#discussion_r923849121

**Comment by joosthooz** [comment]
Would this be a file integrity check using a checksum in the repo file? Or a verification of a dataset by checksumming the files and then comparing to what is in the metadata file (that was generated when the instance was created)?
