### ISSUE TITLE
Possibly unify url and base_url

### ISSUE THREAD

**Issue by joosthooz** [conbench/datalogistik#110]
What do you think about using `url` for both types, and then treating it as a base URL IFF the files have `rel_paths` associated with them?

_Originally posted by @jonkeane in https://github.com/conbench/datalogistik/pull/101#discussion_r994785725_

Keep in mind that in that case, `rel_path` and the filename in the url must be identical, otherwise validation will fail.

**Comment by austin3dickey** [comment]
+1
