### ISSUE TITLE
Solidify cache hierarchy level names

### ISSUE THREAD

**Issue by austin3dickey** [conbench/datalogistik#13]
- [x] Dataset API creates a directory with given name, containing part-### files. When downloading or generating, the files are created directly. This should be unified (probably: no partitioning -> plain files, otherwise directory with part-### files).
- [x] Come up with better names for the cache hierarchy level names (e.g. partitioning-by-rows-### and scale-factor-###)

**Comment by joosthooz** [comment]
I added `scalefactor_` and `partitioning_` prefixes. Or do we like `partitioning-by-rows-###` and `scale-factor-###` better?

**Comment by austin3dickey** [comment]
`scalefactor_` and `partitioning_` sounds good to me!
