### ISSUE TITLE
Interface for getting metadata

### ISSUE THREAD

**Issue by alistaire47** [conbench/datalogistik#54]
Frequently in benchmarks we validate results by checking attributes of the results, e.g. that reading a CSV into a dataframe was successful because the number of rows and cols match stored metadata. We don't want to store this metadata in benchmarks; it should be parameterized with the data source. It does exist in datalogistik metadata files, but are we ok with benchmarks parsing those? If not, I think we need a command to access metadata, e.g. `datalogistik metadata type_floats` or whatever. Mostly we'll just want dims, but maybe sometimes schemas or other metadata too? So probably a JSON return if we do want a command.

**Comment by jonkeane** [comment]
This might be effectively duplicated by #77

**Comment by jonkeane** [comment]
I'm going to close this now that we have dims in the standard output. We can always reopen it if we find we need a separate metadata command, but I don't think we need one right now for the MVP (and I'm a bit skeptical we'll ever need one).
