### ISSUE TITLE
ndjson file conversion support

### ISSUE THREAD

**Issue by alistaire47** [conbench/datalogistik#55]
[We currently benchmark ndjson file reading](https://github.com/voltrondata-labs/arrowbench/blob/main/R/bm-read-json.R), which requires converting a dataframe to an ndjson file, which can be either uncompressed (`.json`) or gzipped (`.json.gz`). Nulls should be explicit, i.e. `..., "col3": null, ...`.

**Comment by jonkeane** [comment]
We _miiiight_ defer this one from MVP. It's cool that we have this benchmark, but if it's not operational for a little bit while we get datalogistik in, that would be _ok_ by me.

**Comment by joosthooz** [comment]
We may need to use another library to write ndjson, because pyarrow does not support writing ndjson...
