### ISSUE TITLE
Add `dims` to the output result

### ISSUE THREAD

**Issue by jonkeane** [conbench/datalogistik#77]
Since many downstream consumers will want to know the dimensions we truly expect for output validation, we should provide that in the JSON as well.

**Comment by joosthooz** [comment]
The difficulty with this is that dim is a per-table property (although we currently store it as a field in `dataset.py`. So we should either output a list of dims that matches the order of the `tables` list of paths, or change the `tables` output to a list of entries that contain a path and a dim (and maybe some other properties).
